//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 13/01/2019 17:05:12
namespace Data.Models
{
    /// <summary>
    /// There are no comments for GroupSingle in the schema.
    /// </summary>
    public partial class GroupSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Group>
    {
        /// <summary>
        /// Initialize a new GroupSingle object.
        /// </summary>
        public GroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new GroupSingle object.
        /// </summary>
        public GroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new GroupSingle object.
        /// </summary>
        public GroupSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Group> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.GroupSingle Parent
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Parent == null))
                {
                    this._Parent = new global::Data.Models.GroupSingle(this.Context, GetPath("Parent"));
                }
                return this._Parent;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.GroupSingle _Parent;
        /// <summary>
        /// There are no comments for Exams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Exam> Exams
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Exams == null))
                {
                    this._Exams = Context.CreateQuery<global::Data.Models.Exam>(GetPath("Exams"));
                }
                return this._Exams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Exam> _Exams;
        /// <summary>
        /// There are no comments for Childs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Group> Childs
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Childs == null))
                {
                    this._Childs = Context.CreateQuery<global::Data.Models.Group>(GetPath("Childs"));
                }
                return this._Childs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Group> _Childs;
        /// <summary>
        /// There are no comments for LimitDecimals in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitDecimal> LimitDecimals
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LimitDecimals == null))
                {
                    this._LimitDecimals = Context.CreateQuery<global::Data.Models.LimitDecimal>(GetPath("LimitDecimals"));
                }
                return this._LimitDecimals;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitDecimal> _LimitDecimals;
    }
    /// <summary>
    /// There are no comments for Group in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Group : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Group object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Group CreateGroup(global::System.Guid ID, string name)
        {
            Group group = new Group();
            group.Id = ID;
            group.Name = name;
            return group;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Initials in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Initials
        {
            get
            {
                return this._Initials;
            }
            set
            {
                this.OnInitialsChanging(value);
                this._Initials = value;
                this.OnInitialsChanged();
                this.OnPropertyChanged("Initials");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Initials;
        partial void OnInitialsChanging(string value);
        partial void OnInitialsChanged();
        /// <summary>
        /// There are no comments for Property ParentId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.Guid> ParentId
        {
            get
            {
                return this._ParentId;
            }
            set
            {
                this.OnParentIdChanging(value);
                this._ParentId = value;
                this.OnParentIdChanged();
                this.OnPropertyChanged("ParentId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.Guid> _ParentId;
        partial void OnParentIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnParentIdChanged();
        /// <summary>
        /// There are no comments for Property MeasureUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string MeasureUnit
        {
            get
            {
                return this._MeasureUnit;
            }
            set
            {
                this.OnMeasureUnitChanging(value);
                this._MeasureUnit = value;
                this.OnMeasureUnitChanged();
                this.OnPropertyChanged("MeasureUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _MeasureUnit;
        partial void OnMeasureUnitChanging(string value);
        partial void OnMeasureUnitChanged();
        /// <summary>
        /// There are no comments for Property Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.Group Parent
        {
            get
            {
                return this._Parent;
            }
            set
            {
                this.OnParentChanging(value);
                this._Parent = value;
                this.OnParentChanged();
                this.OnPropertyChanged("Parent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.Group _Parent;
        partial void OnParentChanging(global::Data.Models.Group value);
        partial void OnParentChanged();
        /// <summary>
        /// There are no comments for Property Exams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.Exam> Exams
        {
            get
            {
                return this._Exams;
            }
            set
            {
                this.OnExamsChanging(value);
                this._Exams = value;
                this.OnExamsChanged();
                this.OnPropertyChanged("Exams");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.Exam> _Exams = new global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.Exam>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnExamsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.Exam> value);
        partial void OnExamsChanged();
        /// <summary>
        /// There are no comments for Property Childs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.Group> Childs
        {
            get
            {
                return this._Childs;
            }
            set
            {
                this.OnChildsChanging(value);
                this._Childs = value;
                this.OnChildsChanged();
                this.OnPropertyChanged("Childs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.Group> _Childs = new global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.Group>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnChildsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.Group> value);
        partial void OnChildsChanged();
        /// <summary>
        /// There are no comments for Property LimitDecimals in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.LimitDecimal> LimitDecimals
        {
            get
            {
                return this._LimitDecimals;
            }
            set
            {
                this.OnLimitDecimalsChanging(value);
                this._LimitDecimals = value;
                this.OnLimitDecimalsChanged();
                this.OnPropertyChanged("LimitDecimals");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.LimitDecimal> _LimitDecimals = new global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.LimitDecimal>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnLimitDecimalsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Data.Models.LimitDecimal> value);
        partial void OnLimitDecimalsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ExamSingle in the schema.
    /// </summary>
    public partial class ExamSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Exam>
    {
        /// <summary>
        /// Initialize a new ExamSingle object.
        /// </summary>
        public ExamSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ExamSingle object.
        /// </summary>
        public ExamSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ExamSingle object.
        /// </summary>
        public ExamSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Exam> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.GroupSingle Group
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Group == null))
                {
                    this._Group = new global::Data.Models.GroupSingle(this.Context, GetPath("Group"));
                }
                return this._Group;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.GroupSingle _Group;
    }
    /// <summary>
    /// There are no comments for Exam in the schema.
    /// </summary>
    /// <KeyProperties>
    /// GroupId
    /// CollectionDate
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("GroupId", "CollectionDate")]
    public abstract partial class Exam : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property GroupId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.Guid> GroupId
        {
            get
            {
                return this._GroupId;
            }
            set
            {
                this.OnGroupIdChanging(value);
                this._GroupId = value;
                this.OnGroupIdChanged();
                this.OnPropertyChanged("GroupId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.Guid> _GroupId;
        partial void OnGroupIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnGroupIdChanged();
        /// <summary>
        /// There are no comments for Property CollectionDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.DateTimeOffset CollectionDate
        {
            get
            {
                return this._CollectionDate;
            }
            set
            {
                this.OnCollectionDateChanging(value);
                this._CollectionDate = value;
                this.OnCollectionDateChanged();
                this.OnPropertyChanged("CollectionDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _CollectionDate;
        partial void OnCollectionDateChanging(global::System.DateTimeOffset value);
        partial void OnCollectionDateChanged();
        /// <summary>
        /// There are no comments for Property Group in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.Group Group
        {
            get
            {
                return this._Group;
            }
            set
            {
                this.OnGroupChanging(value);
                this._Group = value;
                this.OnGroupChanged();
                this.OnPropertyChanged("Group");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.Group _Group;
        partial void OnGroupChanging(global::Data.Models.Group value);
        partial void OnGroupChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ExamDecimalSingle in the schema.
    /// </summary>
    public partial class ExamDecimalSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ExamDecimal>
    {
        /// <summary>
        /// Initialize a new ExamDecimalSingle object.
        /// </summary>
        public ExamDecimalSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ExamDecimalSingle object.
        /// </summary>
        public ExamDecimalSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ExamDecimalSingle object.
        /// </summary>
        public ExamDecimalSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ExamDecimal> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for LimitDenormalized in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.LimitDecimalDenormalizedSingle LimitDenormalized
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LimitDenormalized == null))
                {
                    this._LimitDenormalized = new global::Data.Models.LimitDecimalDenormalizedSingle(this.Context, GetPath("LimitDenormalized"));
                }
                return this._LimitDenormalized;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.LimitDecimalDenormalizedSingle _LimitDenormalized;
        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.GroupSingle Group
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Group == null))
                {
                    this._Group = new global::Data.Models.GroupSingle(this.Context, GetPath("Group"));
                }
                return this._Group;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.GroupSingle _Group;
    }
    /// <summary>
    /// There are no comments for ExamDecimal in the schema.
    /// </summary>
    /// <KeyProperties>
    /// GroupId
    /// CollectionDate
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("GroupId", "CollectionDate")]
    public partial class ExamDecimal : Exam
    {
        /// <summary>
        /// Create a new ExamDecimal object.
        /// </summary>
        /// <param name="collectionDate">Initial value of CollectionDate.</param>
        /// <param name="decimalValue">Initial value of DecimalValue.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static ExamDecimal CreateExamDecimal(global::System.DateTimeOffset collectionDate, decimal decimalValue)
        {
            ExamDecimal examDecimal = new ExamDecimal();
            examDecimal.CollectionDate = collectionDate;
            examDecimal.DecimalValue = decimalValue;
            return examDecimal;
        }
        /// <summary>
        /// There are no comments for Property DecimalValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public decimal DecimalValue
        {
            get
            {
                return this._DecimalValue;
            }
            set
            {
                this.OnDecimalValueChanging(value);
                this._DecimalValue = value;
                this.OnDecimalValueChanged();
                this.OnPropertyChanged("DecimalValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _DecimalValue;
        partial void OnDecimalValueChanging(decimal value);
        partial void OnDecimalValueChanged();
        /// <summary>
        /// There are no comments for Property LimitDenormalized in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.LimitDecimalDenormalized LimitDenormalized
        {
            get
            {
                return this._LimitDenormalized;
            }
            set
            {
                this.OnLimitDenormalizedChanging(value);
                this._LimitDenormalized = value;
                this.OnLimitDenormalizedChanged();
                this.OnPropertyChanged("LimitDenormalized");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.LimitDecimalDenormalized _LimitDenormalized;
        partial void OnLimitDenormalizedChanging(global::Data.Models.LimitDecimalDenormalized value);
        partial void OnLimitDenormalizedChanged();
    }
    /// <summary>
    /// There are no comments for LimitDecimalDenormalizedSingle in the schema.
    /// </summary>
    public partial class LimitDecimalDenormalizedSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<LimitDecimalDenormalized>
    {
        /// <summary>
        /// Initialize a new LimitDecimalDenormalizedSingle object.
        /// </summary>
        public LimitDecimalDenormalizedSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LimitDecimalDenormalizedSingle object.
        /// </summary>
        public LimitDecimalDenormalizedSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LimitDecimalDenormalizedSingle object.
        /// </summary>
        public LimitDecimalDenormalizedSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<LimitDecimalDenormalized> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Exam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.ExamDecimalSingle Exam
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Exam == null))
                {
                    this._Exam = new global::Data.Models.ExamDecimalSingle(this.Context, GetPath("Exam"));
                }
                return this._Exam;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.ExamDecimalSingle _Exam;
    }
    /// <summary>
    /// There are no comments for LimitDecimalDenormalized in the schema.
    /// </summary>
    /// <KeyProperties>
    /// GroupId
    /// CollectionDate
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("GroupId", "CollectionDate")]
    public partial class LimitDecimalDenormalized : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property GroupId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.Guid> GroupId
        {
            get
            {
                return this._GroupId;
            }
            set
            {
                this.OnGroupIdChanging(value);
                this._GroupId = value;
                this.OnGroupIdChanged();
                this.OnPropertyChanged("GroupId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.Guid> _GroupId;
        partial void OnGroupIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnGroupIdChanged();
        /// <summary>
        /// There are no comments for Property CollectionDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.DateTimeOffset> CollectionDate
        {
            get
            {
                return this._CollectionDate;
            }
            set
            {
                this.OnCollectionDateChanging(value);
                this._CollectionDate = value;
                this.OnCollectionDateChanged();
                this.OnPropertyChanged("CollectionDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CollectionDate;
        partial void OnCollectionDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCollectionDateChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property MinType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::Data.Models.MinTypeEnum> MinType
        {
            get
            {
                return this._MinType;
            }
            set
            {
                this.OnMinTypeChanging(value);
                this._MinType = value;
                this.OnMinTypeChanged();
                this.OnPropertyChanged("MinType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::Data.Models.MinTypeEnum> _MinType;
        partial void OnMinTypeChanging(global::System.Nullable<global::Data.Models.MinTypeEnum> value);
        partial void OnMinTypeChanged();
        /// <summary>
        /// There are no comments for Property Min in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<decimal> Min
        {
            get
            {
                return this._Min;
            }
            set
            {
                this.OnMinChanging(value);
                this._Min = value;
                this.OnMinChanged();
                this.OnPropertyChanged("Min");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<decimal> _Min;
        partial void OnMinChanging(global::System.Nullable<decimal> value);
        partial void OnMinChanged();
        /// <summary>
        /// There are no comments for Property MaxType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::Data.Models.MaxTypeEnum> MaxType
        {
            get
            {
                return this._MaxType;
            }
            set
            {
                this.OnMaxTypeChanging(value);
                this._MaxType = value;
                this.OnMaxTypeChanged();
                this.OnPropertyChanged("MaxType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::Data.Models.MaxTypeEnum> _MaxType;
        partial void OnMaxTypeChanging(global::System.Nullable<global::Data.Models.MaxTypeEnum> value);
        partial void OnMaxTypeChanged();
        /// <summary>
        /// There are no comments for Property Max in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<decimal> Max
        {
            get
            {
                return this._Max;
            }
            set
            {
                this.OnMaxChanging(value);
                this._Max = value;
                this.OnMaxChanged();
                this.OnPropertyChanged("Max");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<decimal> _Max;
        partial void OnMaxChanging(global::System.Nullable<decimal> value);
        partial void OnMaxChanged();
        /// <summary>
        /// There are no comments for Property Color in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this.OnColorChanging(value);
                this._Color = value;
                this.OnColorChanged();
                this.OnPropertyChanged("Color");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _Color;
        partial void OnColorChanging(global::System.Nullable<int> value);
        partial void OnColorChanged();
        /// <summary>
        /// There are no comments for Property Exam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.ExamDecimal Exam
        {
            get
            {
                return this._Exam;
            }
            set
            {
                this.OnExamChanging(value);
                this._Exam = value;
                this.OnExamChanged();
                this.OnPropertyChanged("Exam");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.ExamDecimal _Exam;
        partial void OnExamChanging(global::Data.Models.ExamDecimal value);
        partial void OnExamChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LimitStringDenormalizedSingle in the schema.
    /// </summary>
    public partial class LimitStringDenormalizedSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<LimitStringDenormalized>
    {
        /// <summary>
        /// Initialize a new LimitStringDenormalizedSingle object.
        /// </summary>
        public LimitStringDenormalizedSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LimitStringDenormalizedSingle object.
        /// </summary>
        public LimitStringDenormalizedSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LimitStringDenormalizedSingle object.
        /// </summary>
        public LimitStringDenormalizedSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<LimitStringDenormalized> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Exam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.ExamStringSingle Exam
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Exam == null))
                {
                    this._Exam = new global::Data.Models.ExamStringSingle(this.Context, GetPath("Exam"));
                }
                return this._Exam;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.ExamStringSingle _Exam;
    }
    /// <summary>
    /// There are no comments for LimitStringDenormalized in the schema.
    /// </summary>
    /// <KeyProperties>
    /// GroupId
    /// CollectionDate
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("GroupId", "CollectionDate")]
    public partial class LimitStringDenormalized : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property GroupId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.Guid> GroupId
        {
            get
            {
                return this._GroupId;
            }
            set
            {
                this.OnGroupIdChanging(value);
                this._GroupId = value;
                this.OnGroupIdChanged();
                this.OnPropertyChanged("GroupId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.Guid> _GroupId;
        partial void OnGroupIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnGroupIdChanged();
        /// <summary>
        /// There are no comments for Property CollectionDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.DateTimeOffset> CollectionDate
        {
            get
            {
                return this._CollectionDate;
            }
            set
            {
                this.OnCollectionDateChanging(value);
                this._CollectionDate = value;
                this.OnCollectionDateChanged();
                this.OnPropertyChanged("CollectionDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CollectionDate;
        partial void OnCollectionDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCollectionDateChanged();
        /// <summary>
        /// There are no comments for Property Expected in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Expected
        {
            get
            {
                return this._Expected;
            }
            set
            {
                this.OnExpectedChanging(value);
                this._Expected = value;
                this.OnExpectedChanged();
                this.OnPropertyChanged("Expected");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Expected;
        partial void OnExpectedChanging(string value);
        partial void OnExpectedChanged();
        /// <summary>
        /// There are no comments for Property Color in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this.OnColorChanging(value);
                this._Color = value;
                this.OnColorChanged();
                this.OnPropertyChanged("Color");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _Color;
        partial void OnColorChanging(global::System.Nullable<int> value);
        partial void OnColorChanged();
        /// <summary>
        /// There are no comments for Property Exam in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.ExamString Exam
        {
            get
            {
                return this._Exam;
            }
            set
            {
                this.OnExamChanging(value);
                this._Exam = value;
                this.OnExamChanged();
                this.OnPropertyChanged("Exam");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.ExamString _Exam;
        partial void OnExamChanging(global::Data.Models.ExamString value);
        partial void OnExamChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ExamStringSingle in the schema.
    /// </summary>
    public partial class ExamStringSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ExamString>
    {
        /// <summary>
        /// Initialize a new ExamStringSingle object.
        /// </summary>
        public ExamStringSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ExamStringSingle object.
        /// </summary>
        public ExamStringSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ExamStringSingle object.
        /// </summary>
        public ExamStringSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ExamString> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for LimitDenormalized in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.LimitStringDenormalizedSingle LimitDenormalized
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._LimitDenormalized == null))
                {
                    this._LimitDenormalized = new global::Data.Models.LimitStringDenormalizedSingle(this.Context, GetPath("LimitDenormalized"));
                }
                return this._LimitDenormalized;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.LimitStringDenormalizedSingle _LimitDenormalized;
        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.GroupSingle Group
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Group == null))
                {
                    this._Group = new global::Data.Models.GroupSingle(this.Context, GetPath("Group"));
                }
                return this._Group;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.GroupSingle _Group;
    }
    /// <summary>
    /// There are no comments for ExamString in the schema.
    /// </summary>
    /// <KeyProperties>
    /// GroupId
    /// CollectionDate
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("GroupId", "CollectionDate")]
    public partial class ExamString : Exam
    {
        /// <summary>
        /// Create a new ExamString object.
        /// </summary>
        /// <param name="collectionDate">Initial value of CollectionDate.</param>
        /// <param name="stringValue">Initial value of StringValue.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static ExamString CreateExamString(global::System.DateTimeOffset collectionDate, string stringValue)
        {
            ExamString examString = new ExamString();
            examString.CollectionDate = collectionDate;
            examString.StringValue = stringValue;
            return examString;
        }
        /// <summary>
        /// There are no comments for Property StringValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string StringValue
        {
            get
            {
                return this._StringValue;
            }
            set
            {
                this.OnStringValueChanging(value);
                this._StringValue = value;
                this.OnStringValueChanged();
                this.OnPropertyChanged("StringValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _StringValue;
        partial void OnStringValueChanging(string value);
        partial void OnStringValueChanged();
        /// <summary>
        /// There are no comments for Property LimitDenormalized in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.LimitStringDenormalized LimitDenormalized
        {
            get
            {
                return this._LimitDenormalized;
            }
            set
            {
                this.OnLimitDenormalizedChanging(value);
                this._LimitDenormalized = value;
                this.OnLimitDenormalizedChanged();
                this.OnPropertyChanged("LimitDenormalized");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.LimitStringDenormalized _LimitDenormalized;
        partial void OnLimitDenormalizedChanging(global::Data.Models.LimitStringDenormalized value);
        partial void OnLimitDenormalizedChanged();
    }
    /// <summary>
    /// There are no comments for LimitDecimalSingle in the schema.
    /// </summary>
    public partial class LimitDecimalSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<LimitDecimal>
    {
        /// <summary>
        /// Initialize a new LimitDecimalSingle object.
        /// </summary>
        public LimitDecimalSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LimitDecimalSingle object.
        /// </summary>
        public LimitDecimalSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LimitDecimalSingle object.
        /// </summary>
        public LimitDecimalSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<LimitDecimal> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Last in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.LimitDecimalSingle Last
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Last == null))
                {
                    this._Last = new global::Data.Models.LimitDecimalSingle(this.Context, GetPath("Last"));
                }
                return this._Last;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.LimitDecimalSingle _Last;
        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.GroupSingle Group
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Group == null))
                {
                    this._Group = new global::Data.Models.GroupSingle(this.Context, GetPath("Group"));
                }
                return this._Group;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.GroupSingle _Group;
    }
    /// <summary>
    /// There are no comments for LimitDecimal in the schema.
    /// </summary>
    /// <KeyProperties>
    /// GroupId
    /// Priority
    /// Max
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("GroupId", "Priority", "Max")]
    public partial class LimitDecimal : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new LimitDecimal object.
        /// </summary>
        /// <param name="max">Initial value of Max.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static LimitDecimal CreateLimitDecimal(decimal max)
        {
            LimitDecimal limitDecimal = new LimitDecimal();
            limitDecimal.Max = max;
            return limitDecimal;
        }
        /// <summary>
        /// There are no comments for Property GroupId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<global::System.Guid> GroupId
        {
            get
            {
                return this._GroupId;
            }
            set
            {
                this.OnGroupIdChanging(value);
                this._GroupId = value;
                this.OnGroupIdChanged();
                this.OnPropertyChanged("GroupId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.Guid> _GroupId;
        partial void OnGroupIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnGroupIdChanged();
        /// <summary>
        /// There are no comments for Property Priority in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                this.OnPriorityChanging(value);
                this._Priority = value;
                this.OnPriorityChanged();
                this.OnPropertyChanged("Priority");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _Priority;
        partial void OnPriorityChanging(global::System.Nullable<int> value);
        partial void OnPriorityChanged();
        /// <summary>
        /// There are no comments for Property Max in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public decimal Max
        {
            get
            {
                return this._Max;
            }
            set
            {
                this.OnMaxChanging(value);
                this._Max = value;
                this.OnMaxChanged();
                this.OnPropertyChanged("Max");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private decimal _Max;
        partial void OnMaxChanging(decimal value);
        partial void OnMaxChanged();
        /// <summary>
        /// There are no comments for Property Min in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<decimal> Min
        {
            get
            {
                return this._Min;
            }
            set
            {
                this.OnMinChanging(value);
                this._Min = value;
                this.OnMinChanged();
                this.OnPropertyChanged("Min");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<decimal> _Min;
        partial void OnMinChanging(global::System.Nullable<decimal> value);
        partial void OnMinChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Last in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.LimitDecimal Last
        {
            get
            {
                return this._Last;
            }
            set
            {
                this.OnLastChanging(value);
                this._Last = value;
                this.OnLastChanged();
                this.OnPropertyChanged("Last");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.LimitDecimal _Last;
        partial void OnLastChanging(global::Data.Models.LimitDecimal value);
        partial void OnLastChanged();
        /// <summary>
        /// There are no comments for Property Group in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Data.Models.Group Group
        {
            get
            {
                return this._Group;
            }
            set
            {
                this.OnGroupChanging(value);
                this._Group = value;
                this.OnGroupChanged();
                this.OnPropertyChanged("Group");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Data.Models.Group _Group;
        partial void OnGroupChanging(global::Data.Models.Group value);
        partial void OnGroupChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MinTypeEnum in the schema.
    /// </summary>
    public enum MinTypeEnum
    {
        BiggerThan = 1,
        EqualsOrBiggerThan = 2
    }
    /// <summary>
    /// There are no comments for MaxTypeEnum in the schema.
    /// </summary>
    public enum MaxTypeEnum
    {
        SmallThan = 1,
        SmallOrEqualsThan = 2
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Data.Models.Group as global::Data.Models.GroupSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Data.Models.GroupSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Group> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Data.Models.GroupSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.Group as global::Data.Models.GroupSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Data.Models.GroupSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Group> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Data.Models.GroupSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.Exam as global::Data.Models.ExamSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Data.Models.ExamSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Exam> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Data.Models.ExamSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.Exam as global::Data.Models.ExamSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="groupId">The value of groupId</param>
        /// <param name="collectionDate">The value of collectionDate</param>
        public static global::Data.Models.ExamSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Exam> source,
            global::System.Nullable<global::System.Guid> groupId, 
            global::System.DateTimeOffset collectionDate)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "GroupId", groupId }, 
                { "CollectionDate", collectionDate }
            };
            return new global::Data.Models.ExamSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.ExamDecimal as global::Data.Models.ExamDecimalSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Data.Models.ExamDecimalSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.ExamDecimal> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Data.Models.ExamDecimalSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.ExamDecimal as global::Data.Models.ExamDecimalSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="groupId">The value of groupId</param>
        /// <param name="collectionDate">The value of collectionDate</param>
        public static global::Data.Models.ExamDecimalSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.ExamDecimal> source,
            global::System.Nullable<global::System.Guid> groupId, 
            global::System.DateTimeOffset collectionDate)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "GroupId", groupId }, 
                { "CollectionDate", collectionDate }
            };
            return new global::Data.Models.ExamDecimalSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Data.Models.Exam to its derived type global::Data.Models.ExamDecimal
        /// </summary>
        /// <param name="source">source entity</param>
        public static global::Data.Models.ExamDecimalSingle CastToExamDecimal(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Data.Models.Exam> source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Data.Models.ExamDecimal> query = source.CastTo<global::Data.Models.ExamDecimal>();
            return new global::Data.Models.ExamDecimalSingle(source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.LimitDecimalDenormalized as global::Data.Models.LimitDecimalDenormalizedSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Data.Models.LimitDecimalDenormalizedSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitDecimalDenormalized> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Data.Models.LimitDecimalDenormalizedSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.LimitDecimalDenormalized as global::Data.Models.LimitDecimalDenormalizedSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="groupId">The value of groupId</param>
        /// <param name="collectionDate">The value of collectionDate</param>
        public static global::Data.Models.LimitDecimalDenormalizedSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitDecimalDenormalized> source,
            global::System.Nullable<global::System.Guid> groupId, 
            global::System.Nullable<global::System.DateTimeOffset> collectionDate)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "GroupId", groupId }, 
                { "CollectionDate", collectionDate }
            };
            return new global::Data.Models.LimitDecimalDenormalizedSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.LimitStringDenormalized as global::Data.Models.LimitStringDenormalizedSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Data.Models.LimitStringDenormalizedSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitStringDenormalized> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Data.Models.LimitStringDenormalizedSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.LimitStringDenormalized as global::Data.Models.LimitStringDenormalizedSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="groupId">The value of groupId</param>
        /// <param name="collectionDate">The value of collectionDate</param>
        public static global::Data.Models.LimitStringDenormalizedSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitStringDenormalized> source,
            global::System.Nullable<global::System.Guid> groupId, 
            global::System.Nullable<global::System.DateTimeOffset> collectionDate)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "GroupId", groupId }, 
                { "CollectionDate", collectionDate }
            };
            return new global::Data.Models.LimitStringDenormalizedSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.ExamString as global::Data.Models.ExamStringSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Data.Models.ExamStringSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.ExamString> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Data.Models.ExamStringSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.ExamString as global::Data.Models.ExamStringSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="groupId">The value of groupId</param>
        /// <param name="collectionDate">The value of collectionDate</param>
        public static global::Data.Models.ExamStringSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.ExamString> source,
            global::System.Nullable<global::System.Guid> groupId, 
            global::System.DateTimeOffset collectionDate)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "GroupId", groupId }, 
                { "CollectionDate", collectionDate }
            };
            return new global::Data.Models.ExamStringSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Data.Models.Exam to its derived type global::Data.Models.ExamString
        /// </summary>
        /// <param name="source">source entity</param>
        public static global::Data.Models.ExamStringSingle CastToExamString(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Data.Models.Exam> source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Data.Models.ExamString> query = source.CastTo<global::Data.Models.ExamString>();
            return new global::Data.Models.ExamStringSingle(source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.LimitDecimal as global::Data.Models.LimitDecimalSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Data.Models.LimitDecimalSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitDecimal> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Data.Models.LimitDecimalSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Data.Models.LimitDecimal as global::Data.Models.LimitDecimalSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="groupId">The value of groupId</param>
        /// <param name="priority">The value of priority</param>
        /// <param name="max">The value of max</param>
        public static global::Data.Models.LimitDecimalSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitDecimal> source,
            global::System.Nullable<global::System.Guid> groupId, 
            global::System.Nullable<int> priority, 
            decimal max)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "GroupId", groupId }, 
                { "Priority", priority }, 
                { "Max", max }
            };
            return new global::Data.Models.LimitDecimalSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Group> Groups
        {
            get
            {
                if ((this._Groups == null))
                {
                    this._Groups = base.CreateQuery<global::Data.Models.Group>("Groups");
                }
                return this._Groups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Group> _Groups;
        /// <summary>
        /// There are no comments for Exams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Exam> Exams
        {
            get
            {
                if ((this._Exams == null))
                {
                    this._Exams = base.CreateQuery<global::Data.Models.Exam>("Exams");
                }
                return this._Exams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Exam> _Exams;
        /// <summary>
        /// There are no comments for ExamDecimals in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.ExamDecimal> ExamDecimals
        {
            get
            {
                if ((this._ExamDecimals == null))
                {
                    this._ExamDecimals = base.CreateQuery<global::Data.Models.ExamDecimal>("ExamDecimals");
                }
                return this._ExamDecimals;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.ExamDecimal> _ExamDecimals;
        /// <summary>
        /// There are no comments for LimitDecimalDenormalizeds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitDecimalDenormalized> LimitDecimalDenormalizeds
        {
            get
            {
                if ((this._LimitDecimalDenormalizeds == null))
                {
                    this._LimitDecimalDenormalizeds = base.CreateQuery<global::Data.Models.LimitDecimalDenormalized>("LimitDecimalDenormalizeds");
                }
                return this._LimitDecimalDenormalizeds;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitDecimalDenormalized> _LimitDecimalDenormalizeds;
        /// <summary>
        /// There are no comments for LimitStringDenormalizeds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitStringDenormalized> LimitStringDenormalizeds
        {
            get
            {
                if ((this._LimitStringDenormalizeds == null))
                {
                    this._LimitStringDenormalizeds = base.CreateQuery<global::Data.Models.LimitStringDenormalized>("LimitStringDenormalizeds");
                }
                return this._LimitStringDenormalizeds;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.LimitStringDenormalized> _LimitStringDenormalizeds;
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToGroups(global::Data.Models.Group group)
        {
            base.AddObject("Groups", group);
        }
        /// <summary>
        /// There are no comments for Exams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToExams(global::Data.Models.Exam exam)
        {
            base.AddObject("Exams", exam);
        }
        /// <summary>
        /// There are no comments for ExamDecimals in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToExamDecimals(global::Data.Models.ExamDecimal examDecimal)
        {
            base.AddObject("ExamDecimals", examDecimal);
        }
        /// <summary>
        /// There are no comments for LimitDecimalDenormalizeds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToLimitDecimalDenormalizeds(global::Data.Models.LimitDecimalDenormalized limitDecimalDenormalized)
        {
            base.AddObject("LimitDecimalDenormalizeds", limitDecimalDenormalized);
        }
        /// <summary>
        /// There are no comments for LimitStringDenormalizeds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToLimitStringDenormalizeds(global::Data.Models.LimitStringDenormalized limitStringDenormalized)
        {
            base.AddObject("LimitStringDenormalizeds", limitStringDenormalized);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Data.Models"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Group"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Initials"" Type=""Edm.String"" />
        <Property Name=""ParentId"" Type=""Edm.Guid"" />
        <Property Name=""MeasureUnit"" Type=""Edm.String"" />
        <NavigationProperty Name=""Parent"" Type=""Data.Models.Group"">
          <ReferentialConstraint Property=""ParentId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""Exams"" Type=""Collection(Data.Models.Exam)"" />
        <NavigationProperty Name=""Childs"" Type=""Collection(Data.Models.Group)"" />
        <NavigationProperty Name=""LimitDecimals"" Type=""Collection(Data.Models.LimitDecimal)"" />
      </EntityType>
      <EntityType Name=""Exam"" Abstract=""true"">
        <Key>
          <PropertyRef Name=""GroupId"" />
          <PropertyRef Name=""CollectionDate"" />
        </Key>
        <Property Name=""GroupId"" Type=""Edm.Guid"" />
        <Property Name=""CollectionDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <NavigationProperty Name=""Group"" Type=""Data.Models.Group"">
          <ReferentialConstraint Property=""GroupId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""ExamDecimal"" BaseType=""Data.Models.Exam"">
        <Property Name=""DecimalValue"" Type=""Edm.Decimal"" Nullable=""false"" />
        <NavigationProperty Name=""LimitDenormalized"" Type=""Data.Models.LimitDecimalDenormalized"" />
      </EntityType>
      <EntityType Name=""LimitDecimalDenormalized"">
        <Key>
          <PropertyRef Name=""GroupId"" />
          <PropertyRef Name=""CollectionDate"" />
        </Key>
        <Property Name=""GroupId"" Type=""Edm.Guid"" />
        <Property Name=""CollectionDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""MinType"" Type=""Data.Models.MinTypeEnum"" />
        <Property Name=""Min"" Type=""Edm.Decimal"" />
        <Property Name=""MaxType"" Type=""Data.Models.MaxTypeEnum"" />
        <Property Name=""Max"" Type=""Edm.Decimal"" />
        <Property Name=""Color"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""Exam"" Type=""Data.Models.ExamDecimal"">
          <ReferentialConstraint Property=""GroupId"" ReferencedProperty=""GroupId"" />
          <ReferentialConstraint Property=""CollectionDate"" ReferencedProperty=""CollectionDate"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""LimitStringDenormalized"">
        <Key>
          <PropertyRef Name=""GroupId"" />
          <PropertyRef Name=""CollectionDate"" />
        </Key>
        <Property Name=""GroupId"" Type=""Edm.Guid"" />
        <Property Name=""CollectionDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Expected"" Type=""Edm.String"" />
        <Property Name=""Color"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""Exam"" Type=""Data.Models.ExamString"">
          <ReferentialConstraint Property=""GroupId"" ReferencedProperty=""GroupId"" />
          <ReferentialConstraint Property=""CollectionDate"" ReferencedProperty=""CollectionDate"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""ExamString"" BaseType=""Data.Models.Exam"">
        <Property Name=""StringValue"" Type=""Edm.String"" Nullable=""false"" />
        <NavigationProperty Name=""LimitDenormalized"" Type=""Data.Models.LimitStringDenormalized"" />
      </EntityType>
      <EntityType Name=""LimitDecimal"">
        <Key>
          <PropertyRef Name=""GroupId"" />
          <PropertyRef Name=""Priority"" />
          <PropertyRef Name=""Max"" />
        </Key>
        <Property Name=""GroupId"" Type=""Edm.Guid"" />
        <Property Name=""Priority"" Type=""Edm.Int32"" />
        <Property Name=""Max"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""Min"" Type=""Edm.Decimal"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <NavigationProperty Name=""Last"" Type=""Data.Models.LimitDecimal"">
          <ReferentialConstraint Property=""Priority"" ReferencedProperty=""Priority"" />
          <ReferentialConstraint Property=""Min"" ReferencedProperty=""Max"" />
        </NavigationProperty>
        <NavigationProperty Name=""Group"" Type=""Data.Models.Group"">
          <ReferentialConstraint Property=""GroupId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
      </EntityType>
      <EnumType Name=""MinTypeEnum"">
        <Member Name=""BiggerThan"" Value=""1"" />
        <Member Name=""EqualsOrBiggerThan"" Value=""2"" />
      </EnumType>
      <EnumType Name=""MaxTypeEnum"">
        <Member Name=""SmallThan"" Value=""1"" />
        <Member Name=""SmallOrEqualsThan"" Value=""2"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Action Name=""BulkInsert"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""Collection(Data.Models.Exam)"" />
        <Parameter Name=""Exams"" Type=""Collection(Data.Models.Exam)"" />
      </Action>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Groups"" EntityType=""Data.Models.Group"">
          <NavigationPropertyBinding Path=""Parent"" Target=""Groups"" />
          <NavigationPropertyBinding Path=""Exams"" Target=""Exams"" />
          <NavigationPropertyBinding Path=""Childs"" Target=""Groups"" />
        </EntitySet>
        <EntitySet Name=""Exams"" EntityType=""Data.Models.Exam"">
          <NavigationPropertyBinding Path=""Group"" Target=""Groups"" />
          <NavigationPropertyBinding Path=""Data.Models.ExamDecimal/LimitDenormalized"" Target=""LimitDecimalDenormalizeds"" />
          <NavigationPropertyBinding Path=""Data.Models.ExamString/LimitDenormalized"" Target=""LimitStringDenormalizeds"" />
        </EntitySet>
        <EntitySet Name=""ExamDecimals"" EntityType=""Data.Models.ExamDecimal"">
          <NavigationPropertyBinding Path=""Group"" Target=""Groups"" />
          <NavigationPropertyBinding Path=""LimitDenormalized"" Target=""LimitDecimalDenormalizeds"" />
        </EntitySet>
        <EntitySet Name=""LimitDecimalDenormalizeds"" EntityType=""Data.Models.LimitDecimalDenormalized"">
          <NavigationPropertyBinding Path=""Exam"" Target=""ExamDecimals"" />
        </EntitySet>
        <EntitySet Name=""LimitStringDenormalizeds"" EntityType=""Data.Models.LimitStringDenormalized"">
          <NavigationPropertyBinding Path=""Exam"" Target=""Exams"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// There are no comments for BulkInsert in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuery BulkInsert(this global::Microsoft.OData.Client.DataServiceQuery<global::Data.Models.Exam> source, global::System.Collections.Generic.ICollection<global::Data.Models.Exam> Exams)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery(source.Context, source.AppendRequestUri("BulkInsert"), new global::Microsoft.OData.Client.BodyOperationParameter("Exams", Exams));
        }
    }
}
